### PR TITLE
add should select multiple to search and select pane

### PR DESCRIPTION
**Pull request by seveibar**

### CODE REVIEW

**Review by codetheweb — APPROVED** [review]

**Comment by rchodava** [comment]
Sorry, don't quite understand the search and select pane. I thought maybe this was something left over historically - that we first had choosing a provider as part of the connect webviews and then moved selection of provider to dashboard instead. 

But I guess it actually makes sense the other way around, started in dashboard and we want to move it to webviews. I guess it makes sense for API consumers to have it as part of webviews. Is this flag to force selection of more than 1 provider, why would you want that? Wouldn't you just create separate webviews for separate providers?

**Comment by seveibar** [comment]
> Sorry, don't quite understand the search and select pane. I thought maybe this was something left over historically - that we first had choosing a provider as part of the connect webviews and then moved selection of provider to dashboard instead.
> 
> But I guess it actually makes sense the other way around, started in dashboard and we want to move it to webviews. I guess it makes sense for API consumers to have it as part of webviews so once they create a webview, their users can choose a provider within the webview flow. Is this flag to force selection of more than 1 provider, why would you want that? Wouldn't you just create separate webviews for separate providers?

Only one provider will ever be selected, this pane is re-used for device selection.

The provider can be selected on the webview or if a single provided is passed via `{ "accepted_providers": ["schlage"] }` we skip the search_and_select_pane

**Comment by rchodava** [comment]
So should_select_multiple is to allow forcing more than 1 device to be selected? In what scenarios do we want to force that? Wouldn't it be better to have something like select_all_by_default?

**Comment by seveibar** [comment]
we could revise the name, it's not forcing multiple to be selected, rather it's saying you _can_ select multiple. E.g. you might want to select all the locks to your house

**Comment by seveibar** [comment]
Maybe `can_select_multiple`

**Comment by seveibar** [comment]
CC @itsmehul

**Review by rchodava — APPROVED** [review]

**Comment by seveibar** [comment]
looks good!

**Pull request merged**
